import type {
  Appointment,
  CRMLog,
  Customer,
  JobAssignment,
  Message,
  Payment,
  Project,
  Quote,
  ServiceRequest,
  Subcontractor,
  SubcontractorApplication,
  Upload,
} from "@/types";

export const customers: Customer[] = [
  {
    id: "cust_1001",
    fullName: "Test Customer",
    email: "test@example.com",
    phone: "(555) 555-1001",
    billingAddress: "123 Main St, Phoenix, AZ",
    propertyAddress: "123 Main St, Phoenix, AZ",
    createdAt: "2026-05-01",
  },
  {
    id: "cust_1002",
    fullName: "Test Deposit Customer",
    email: "deposit@example.com",
    phone: "(555) 555-1002",
    billingAddress: "456 Oak Ave, Mesa, AZ",
    propertyAddress: "456 Oak Ave, Mesa, AZ",
    createdAt: "2026-05-02",
  },
  {
    id: "cust_1003",
    fullName: "Test Paid Customer",
    email: "paid@example.com",
    phone: "(555) 555-1003",
    billingAddress: "789 Desert View Rd, Scottsdale, AZ",
    propertyAddress: "789 Desert View Rd, Scottsdale, AZ",
    createdAt: "2026-05-03",
  },
];

export const serviceRequests: ServiceRequest[] = [
  {
    id: "req_1001",
    customerName: "New Homeowner Request",
    customerEmail: "homeowner@example.com",
    customerPhone: "(555) 555-4001",
    serviceType: "Maintenance & Repair",
    propertyAddress: "101 Palm Ln, Phoenix, AZ",
    propertyType: "Residential",
    occupancyStatus: "Occupied",
    preferredDate: "2026-05-21",
    projectDescription: "Door adjustment, drywall patch, and fixture review.",
    additionalNotes: "Customer prefers a call before quote is prepared.",
    status: "New",
    uploadedFileIds: ["upload_1001"],
    createdAt: "2026-05-13",
  },
  {
    id: "req_1002",
    customerName: "Rental Preservation Request",
    customerEmail: "rental@example.com",
    customerPhone: "(555) 555-4002",
    serviceType: "Property Preservation",
    propertyAddress: "220 Adobe St, Tempe, AZ",
    propertyType: "Rental",
    occupancyStatus: "Vacant",
    preferredDate: "2026-05-23",
    projectDescription: "Vacancy upkeep, trash-out coordination, and readiness check.",
    status: "Quote Needed",
    uploadedFileIds: [],
    createdAt: "2026-05-12",
  },
];

export const quotes: Quote[] = [
  {
    id: "quote_1001",
    quoteNumber: "GPS-1001",
    customerId: "cust_1001",
    customerName: "Test Customer",
    customerEmail: "test@example.com",
    customerPhone: "(555) 555-1001",
    serviceType: "Maintenance & Repair",
    propertyAddress: "123 Main St, Phoenix, AZ",
    amount: 7500,
    depositAmount: 7500,
    amountPaid: 0,
    balanceDue: 7500,
    displayAmount: "$75.00",
    displayDepositAmount: "$75.00",
    displayAmountPaid: "$0.00",
    displayBalanceDue: "$75.00",
    quoteStatus: "Awaiting Payment",
    paymentStatus: "Unpaid",
    serviceStatus: "Awaiting Payment",
    projectId: "proj_1001",
    notes: "Please complete your deposit to confirm scheduling.",
    scheduledDate: "Pending payment",
    assignedTeam: "Scheduling pending",
    createdAt: "2026-05-05",
    expiresAt: "2026-06-05",
  },
  {
    id: "quote_1002",
    quoteNumber: "GPS-1002",
    customerId: "cust_1002",
    customerName: "Test Deposit Customer",
    customerEmail: "deposit@example.com",
    customerPhone: "(555) 555-1002",
    serviceType: "Property Preservation",
    propertyAddress: "456 Oak Ave, Mesa, AZ",
    amount: 10000,
    depositAmount: 5000,
    amountPaid: 5000,
    balanceDue: 5000,
    displayAmount: "$100.00",
    displayDepositAmount: "$50.00",
    displayAmountPaid: "$50.00",
    displayBalanceDue: "$50.00",
    quoteStatus: "Scheduled",
    paymentStatus: "Deposit Paid",
    serviceStatus: "Scheduled",
    projectId: "proj_1002",
    notes: "Deposit received. Preservation service has been scheduled.",
    scheduledDate: "May 22, 2026",
    assignedTeam: "Preservation Coordination Team",
    createdAt: "2026-05-06",
  },
  {
    id: "quote_1003",
    quoteNumber: "GPS-1003",
    customerId: "cust_1003",
    customerName: "Test Paid Customer",
    customerEmail: "paid@example.com",
    customerPhone: "(555) 555-1003",
    serviceType: "Builds & Remodels",
    propertyAddress: "789 Desert View Rd, Scottsdale, AZ",
    amount: 15000,
    depositAmount: 7500,
    amountPaid: 15000,
    balanceDue: 0,
    displayAmount: "$150.00",
    displayDepositAmount: "$75.00",
    displayAmountPaid: "$150.00",
    displayBalanceDue: "$0.00",
    quoteStatus: "Completed",
    paymentStatus: "Paid",
    serviceStatus: "Completed",
    projectId: "proj_1003",
    notes: "Payment received. Remodel support has been completed.",
    scheduledDate: "May 24, 2026",
    assignedTeam: "Builds & Remodels Team",
    createdAt: "2026-05-07",
  },
];

export const projects: Project[] = [
  {
    id: "proj_1001",
    quoteNumber: "GPS-1001",
    customerId: "cust_1001",
    customerName: "Test Customer",
    serviceType: "Maintenance & Repair",
    propertyAddress: "123 Main St, Phoenix, AZ",
    status: "Awaiting Payment",
    paymentStatus: "Unpaid",
    scheduledDate: "Pending payment",
    assignedTeam: "Scheduling pending",
    nextStep: "Complete your deposit to confirm scheduling.",
    notes: "Customer uploaded exterior and kitchen photos for review.",
    uploadedFileIds: ["upload_1001"],
    updatedAt: "2026-05-10",
  },
  {
    id: "proj_1002",
    quoteNumber: "GPS-1002",
    customerId: "cust_1002",
    customerName: "Test Deposit Customer",
    serviceType: "Property Preservation",
    propertyAddress: "456 Oak Ave, Mesa, AZ",
    status: "Scheduled",
    paymentStatus: "Deposit Paid",
    scheduledDate: "May 22, 2026",
    assignedTeam: "Preservation Coordination Team",
    nextStep: "Arrival details will be confirmed before the scheduled visit.",
    notes: "Vacancy upkeep and readiness support scheduled.",
    uploadedFileIds: [],
    updatedAt: "2026-05-11",
  },
  {
    id: "proj_1003",
    quoteNumber: "GPS-1003",
    customerId: "cust_1003",
    customerName: "Test Paid Customer",
    serviceType: "Builds & Remodels",
    propertyAddress: "789 Desert View Rd, Scottsdale, AZ",
    status: "Completed",
    paymentStatus: "Paid",
    scheduledDate: "May 24, 2026",
    assignedTeam: "Builds & Remodels Team",
    nextStep: "Service is complete. Contact Grubel Property Services with follow-up questions.",
    notes: "Interior improvement support completed.",
    uploadedFileIds: ["upload_1002"],
    updatedAt: "2026-05-12",
  },
];

export const payments: Payment[] = [
  {
    id: "pay_1001",
    quoteNumber: "GPS-1001",
    customerId: "cust_1001",
    amount: 7500,
    displayAmount: "$75.00",
    status: "Unpaid",
    method: "Stripe Checkout",
  },
  {
    id: "pay_1002",
    quoteNumber: "GPS-1002",
    customerId: "cust_1002",
    amount: 5000,
    displayAmount: "$50.00",
    status: "Deposit Paid",
    method: "Stripe Checkout",
    paidAt: "2026-05-09",
  },
  {
    id: "pay_1003",
    quoteNumber: "GPS-1003",
    customerId: "cust_1003",
    amount: 15000,
    displayAmount: "$150.00",
    status: "Paid",
    method: "Stripe Checkout",
    paidAt: "2026-05-10",
  },
];

export const appointments: Appointment[] = [
  {
    id: "appt_1001",
    customerName: "New Homeowner Request",
    serviceType: "Maintenance & Repair",
    appointmentDate: "2026-05-21",
    timeWindow: "9:00 AM",
    contactMethod: "Phone",
    status: "Requested",
    notes: "Request came from /request-service intake.",
  },
  {
    id: "appt_1002",
    customerName: "Test Deposit Customer",
    serviceType: "Property Preservation",
    appointmentDate: "2026-05-22",
    timeWindow: "2:00 PM",
    contactMethod: "Video Call",
    status: "Scheduled",
    notes: "Connected to quote GPS-1002.",
    quoteNumber: "GPS-1002",
  },
];

export const uploads: Upload[] = [
  {
    id: "upload_1001",
    relatedId: "req_1001",
    relatedType: "service_request",
    category: "customer_project_photo",
    fileName: "front-entry.jpg",
    fileType: "image/jpeg",
    size: 245000,
    uploadedBy: "New Homeowner Request",
    createdAt: "2026-05-10",
  },
  {
    id: "upload_1002",
    relatedId: "proj_1003",
    relatedType: "project",
    category: "completion_photo",
    fileName: "remodel-complete.png",
    fileType: "image/png",
    size: 310000,
    uploadedBy: "Builds & Remodels Team",
    createdAt: "2026-05-12",
  },
  {
    id: "upload_1003",
    relatedId: "app_1002",
    relatedType: "subcontractor_application",
    category: "insurance_document",
    fileName: "insurance-certificate.pdf",
    fileType: "application/pdf",
    size: 120000,
    uploadedBy: "Commercial Crew LLC",
    createdAt: "2026-05-11",
  },
];

export const messages: Message[] = [
  {
    id: "msg_1001",
    projectId: "proj_1002",
    senderType: "admin",
    senderName: "Grubel Property Services",
    body: "Preservation visit is scheduled. Please confirm gate access if needed.",
    createdAt: "2026-05-11",
  },
  {
    id: "msg_1002",
    projectId: "proj_1003",
    senderType: "admin",
    senderName: "Grubel Property Services",
    body: "Builds & Remodels support is complete and completion photos are on file.",
    createdAt: "2026-05-12",
  },
];

export const applications: SubcontractorApplication[] = [
  {
    id: "app_1001",
    applicationType: "handyman",
    applicantName: "Handyman Applicant",
    email: "handy@example.com",
    phone: "(555) 555-2001",
    experience: "8 years",
    servicesOffered: "General maintenance, drywall, paint, punch-list work",
    serviceAreas: "Phoenix, Mesa, Tempe",
    status: "New",
    uploadedFileIds: [],
    submittedAt: "2026-05-12",
  },
  {
    id: "app_1002",
    applicationType: "commercial",
    applicantName: "Commercial Crew LLC",
    companyName: "Commercial Crew LLC",
    email: "commercial@example.com",
    phone: "(555) 555-2002",
    experience: "Commercial maintenance and tenant improvements",
    servicesOffered: "Commercial repairs, tenant improvements, flooring",
    serviceAreas: "Phoenix metro",
    crewSize: "4",
    licensingInsuranceInfo: "Insurance uploaded; license review pending",
    status: "Pending Review",
    uploadedFileIds: ["upload_1003"],
    submittedAt: "2026-05-11",
  },
];

export const subcontractors: Subcontractor[] = [
  {
    id: "sub_1001",
    fullName: "Approved Repair Partner",
    businessName: "Repair Partner LLC",
    phone: "(555) 555-3001",
    email: "partner@example.com",
    tradeSkills: ["Drywall", "Paint", "Maintenance", "Property Preservation"],
    status: "Active",
    serviceAreas: ["Phoenix", "Mesa", "Tempe"],
    availability: "Weekdays",
    requiredDocuments: ["ID on file", "Insurance pending renewal", "License review"],
    missingDocuments: ["Updated insurance"],
    createdAt: "2026-05-01",
  },
];

export const jobAssignments: JobAssignment[] = [
  {
    id: "job_1001",
    projectId: "proj_1002",
    quoteNumber: "GPS-1002",
    subcontractorId: "sub_1001",
    subcontractorName: "Approved Repair Partner",
    title: "Vacancy readiness punch list",
    propertyAddress: "456 Oak Ave, Mesa, AZ",
    status: "Assigned",
    dueDate: "May 22, 2026",
    notes: "Confirm arrival window and upload completion photos.",
    uploadedFileIds: [],
  },
  {
    id: "job_1002",
    projectId: "proj_1003",
    quoteNumber: "GPS-1003",
    subcontractorId: "sub_1001",
    subcontractorName: "Approved Repair Partner",
    title: "Interior improvement completion photos",
    propertyAddress: "789 Desert View Rd, Scottsdale, AZ",
    status: "Completed",
    dueDate: "May 24, 2026",
    notes: "Completion photos uploaded for internal review.",
    uploadedFileIds: ["upload_1002"],
  },
];

export const crmLogs: CRMLog[] = [
  {
    id: "log_1001",
    date: "2026-05-13",
    type: "Service Request",
    actor: "New Homeowner Request",
    relatedQuoteOrProject: "req_1001",
    status: "New",
    notes: "Maintenance request received with photo upload.",
  },
  {
    id: "log_1002",
    date: "2026-05-11",
    type: "Appointment",
    actor: "Test Deposit Customer",
    relatedQuoteOrProject: "GPS-1002",
    status: "Scheduled",
    notes: "Video call and preservation visit scheduled.",
  },
  {
    id: "log_1003",
    date: "2026-05-10",
    type: "Payment Update",
    actor: "Test Paid Customer",
    relatedQuoteOrProject: "GPS-1003",
    status: "Paid",
    notes: "Payment received through Stripe Checkout.",
  },
  {
    id: "log_1004",
    date: "2026-05-11",
    type: "Subcontractor Action",
    actor: "Commercial Crew LLC",
    relatedQuoteOrProject: "app_1002",
    status: "Pending Review",
    notes: "Commercial subcontractor application received with insurance document.",
  },
];

export function getPortalRecord(quoteNumber: string) {
  const normalized = quoteNumber.trim().toUpperCase();
  const quote = quotes.find((item) => item.quoteNumber === normalized);

  if (!quote) {
    return null;
  }

  const project = projects.find((item) => item.id === quote.projectId);
  const payment = payments.find((item) => item.quoteNumber === quote.quoteNumber);
  const projectUploads = uploads.filter((item) =>
    project?.uploadedFileIds.includes(item.id) || item.relatedId === quote.projectId,
  );
  const projectMessages = messages.filter((item) => item.projectId === quote.projectId);

  return {
    quote,
    project,
    payment,
    uploads: projectUploads,
    messages: projectMessages,
  };
}

// Future Supabase tables:
// customers, service_requests, quotes, projects, payments, appointments,
// uploads, subcontractors, subcontractor_applications, job_assignments, crm_logs.
